config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'
  get 'password_resets/edit'

	root 'static_pages#home'
	get  '/help',    to: 'static_pages#help'
	get  '/about',   to: 'static_pages#about'
	get  '/contact', to: 'static_pages#contact'

	get  '/signup',  to: 'users#new'
	post '/signup',  to: 'users#create'		# Adding a signup route responding to POST requests for unsubmitted signup form
	resources :users


  resources :listings do
    resource :like, :only => [:create, :destroy]
  end

  resources :employeeships, only: [:create, :destroy, :update]


	# HTTP request	URL		Named route		Action		Purpose
	# GET					/login	login_path		new				page for a new session (login)
	#	POST				/login	login_path		create		create a new session (login)
	#	DELETE			/logout	logout_path		destroy		delete a session (log out)
	get    '/login',   to: 'sessions#new'
	post   '/login',   to: 'sessions#create'
	delete '/logout',  to: 'sessions#destroy'

  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/listing.rb
class Listing < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true

  has_many :employeeships, :dependent => :destroy
  #has_many :users, through: :employeeships

  has_many :pending_users,   -> {where employeeships: { status: 0 }}, :through => :employeeships, source: :user
  #has_many :requested_users, -> {where employeeships: { status: 1 }}, :through => :employeeships, source: :user
  has_many :accepted_users,  -> {where employeeships: { status: 1 }}, :through => :employeeships, source: :user


  # User owner listing relation
  belongs_to :user

  # For Likes
  has_many :likes

  def employeeship_for_listing(user, listing)
    Employeeship.where(:user_id => user.id , :listing_id => listing.id).first
  end
end

app/controllers/listings_controller.rb
# index, show, new, edit, create, update and destroy actions
class ListingsController < ApplicationController
  before_action :logged_in_user, only: [:new, :edit, :update, :destroy]
  before_action :user_can_edit,   only: [:edit, :update, :destroy]
 
  def index
    @listings = Listing.paginate(page: params[:page]).per_page(10)
  end

  def show
    @listing = Listing.find(params[:id])
  end

  def new
    @listing = Listing.new
  end

  def edit
    @listing = Listing.find(params[:id])
  end

  def create
    @listing = Listing.new(listing_params)
    @listing.user = current_user

    if @listing.save
      flash[:success] = "Listing was successfully created."
      redirect_to listing_path(@listing)
    else
      render 'new'
    end
  end

  def update
    @listing = Listing.find(params[:id])
    if @listing.update(listing_params)
      flash[:success] = "Listing was successfully updated."
      redirect_to listing_path(@listing)
    else
      render 'edit'
    end
  end

  def destroy
    @listing = Listing.find(params[:id])
    @listing.destroy
    flash[:success] = "Listing was successfully deleted."
    redirect_to listings_path
  end

  private
    def listing_params
      params.require(:listing).permit(:title, :body)
    end

    def user_can_edit
      # @listing = Listing.find(params[:id])
      # logger.debug "User: #{@current_user.inspect}"
      # unless @listing and current_user.can_edit? @listing
      #  redirect_to root_url
      # end
      # @listing = current_user.listings.find_by(id: params[:id])
      # redirect_to root_url if @listing.nil?
      # if current_user.id not equel listing.id.user AND not_admin user SO Redirect to root.
      if current_user != Listing.find(params[:id]).user and !current_user.admin?
        redirect_to root_path
      end
    end
 

end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/edit.html.erb
<h1>Edit Listing</h1>

<div class="row">
  <div class="col-md-6">
    <%= render 'shared/error_messages', obj: @listing %>

    <%= form_for(@listing) do |f| %>
     
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control'%>

      <%= f.label :body %>
      <%= f.text_area :body, cols: 30, rows: 10, class: 'form-control' %>

      <%= f.submit "Save", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/listings/index.html.erb
<h1>Listings</h1>
<%= will_paginate %>

<div class="listings">
  <% @listings.each do |listing| %>
    <h2><%= link_to listing.title, listing_path(listing) %></h2>
    <%= truncate(listing.body, :length => 250) %>
    <%= link_to 'View', listing_path(listing) %>
    <%= link_to 'Edit', edit_listing_path(listing) %>
    <%= link_to 'Delete', listing_path(listing), method: :delete, data: { confirm: "Are you sure?"} %>

<%
=begin %>
    <small>Created by <%= listing.user.name if listing.user %>,
      <%= time_ago_in_words(listing.created_at) %> ago,
      <%= time_ago_in_words(listing.updated_at) %> ago</small>
<%
=end %>

  <% end %>
</div>

app/views/listings/new.html.erb
<% provide(:title, 'New listing') %>
<h1>New listing</h1>

<div class="row">
  <div class="col-md-6">
    <%= form_for @listing do |f| %>
      <%= render 'shared/error_messages', obj: @listing %>
     
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control'%>

      <%= f.label :body %>
      <%= f.text_area :body, cols: 30, rows: 10, class: 'form-control' %>

      <%= f.submit "Create new listing", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/listings/show.html.erb
<h2><%= @listing.title %></h2>
<%= @listing.body %>

<div class="listing-meta">
  <%= link_to 'Edit', edit_listing_path(@listing), class: "btn-sm btn-success" %>
  <%= link_to 'Delete', listing_path(@listing), class: "btn-sm btn-danger", method: :delete, data: { confirm: "Are you sure?"} %>

  <% if logged_in? %>
    <% if current_user.can_join_listing?(@listing.id)  %>
      <%= link_to 'Join Listing', employeeships_path(user_id: current_user, listing_id: @listing.id), class: "btn-sm btn-info", method: :post %>
    <% else %>
      <span class="badge badge-secondary">
          You already added to this Listing
       </span>
    <% end %>
  <% end %>

</div>

<h4>Created by</h4>
<%= @listing.user.name %><br>
<%= user_email(@listing.user) %>

<div id="like">
	<%= render 'likes/like_button', :listing => @listing %>
</div>



<hr>
<h2>Employees - Pending</h2>
<%#= debug @listing.users %>
<% @listing.pending_users.each do |user| %>
  <div>
    <span class="h2"><%= link_to user.name, user_path(user) %></span>

    <% if logged_in? %>
      <% if ( ( employeeship_find(user,@listing).requested_by == employeeship_find(user,@listing).user_id ) &&
              ( current_user.listing_ids.first == employeeship_find(user,@listing).listing_id ) ||
              ( current_user.id == employeeship_find(user,@listing).user_id ) &&
              ( employeeship_find(user,@listing).requested_by != employeeship_find(user,@listing).user_id ) ) %>
        <%= link_to 'Accept', employeeship_path(user_id: user, listing_id: @listing.id), class: "btn-sm btn-success", method: :put, data: { confirm: "Are you sure?"} %>
      <% end %>
    <% end %>

    <% if logged_in? %>
      <% if @listing.user_id == current_user.id || current_user.id == @listing.employeeship_for_listing(user, @listing).user_id %>
        <%= link_to 'Cancel', employeeship_path(user_id: user, listing_id: @listing.id), class: "btn-sm btn-danger", method: :delete, data: { confirm: "Are you sure?"} %>
      <% end %>
    <% end %>
  </div>
<% end %>


<hr>
<h2>Employees - Accepted</h2>
<%#= debug @listing.users %>
<% @listing.accepted_users.each do |user| %>
  <div>
    <span class="h2"><%= link_to user.name, user_path(user) %></span>

  <% if logged_in? %>
    <% if @listing.user_id == current_user.id || current_user.id ==  user.id %>
      <%= link_to 'Delete', employeeship_path(user_id: user, listing_id: @listing.id), class: "btn-sm btn-danger", method: :delete, data: { confirm: "Are you sure?"} %>
    <% end %>
  <% end %>
    
  </div>
<% end %>