config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'
  get 'password_resets/edit'

	root 'static_pages#home'
	get  '/help',    to: 'static_pages#help'
	get  '/about',   to: 'static_pages#about'
	get  '/contact', to: 'static_pages#contact'

	get  '/signup',  to: 'users#new'
	post '/signup',  to: 'users#create'		# Adding a signup route responding to POST requests for unsubmitted signup form
	resources :users


  resources :listings do
    resource :like, :only => [:create, :destroy]
  end

  resources :employeeships, only: [:create, :destroy, :update]


	# HTTP request	URL		Named route		Action		Purpose
	# GET					/login	login_path		new				page for a new session (login)
	#	POST				/login	login_path		create		create a new session (login)
	#	DELETE			/logout	logout_path		destroy		delete a session (log out)
	get    '/login',   to: 'sessions#new'
	post   '/login',   to: 'sessions#create'
	delete '/logout',  to: 'sessions#destroy'

  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token, :activation_token, :reset_token
  before_save   :downcase_email
  before_create :create_activation_digest

  validates :name,  presence: true, length: { maximum: 50 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
   									format: { with: VALID_EMAIL_REGEX },
   									uniqueness: { case_sensitive: false }
	has_secure_password
	validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  has_many :employeeships, :dependent => :destroy
  #has_many :listings, through: :employeeships

  has_many :pending_listings,   -> {where employeeships: { status: 0 }}, :through => :employeeships, source: :listing
  #has_many :requested_listings, -> {where employeeships: { status: 1 }}, :through => :employeeships, source: :listing
  has_many :accepted_listings,  -> {where employeeships: { status: 1 }}, :through => :employeeships, source: :listing

  # User owner listing relation
  has_many :listings, ->{ order "created_at Desc" }

  # For Likes
  has_many :likes

  # enum status: { :pending: 0, accepted: 1 }
  # User role for listings 0 , 1
  enum role: [ :visitor, :beautician ]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :visitor
  end

  def has_like?(listing)
    likes.find_by_listing_id(listing.id)
  end

  # Adding a digest method for use in fixtures
  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token. used for remember user login even if close browser
  def User.new_token
    SecureRandom.urlsafe_base64
  end


  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Returns true if the given token matches the digest.
  # def authenticated?(remember_token)
  #   return false if remember_digest.nil?
  #   BCrypt::Password.new(remember_digest).is_password?(remember_token)
  # end
  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end

  # Activates an account.
  def activate
    # update_attribute(:activated,    true)
    # update_attribute(:activated_at, Time.zone.now)
    update_columns(activated: true, activated_at: Time.zone.now)
  end

  # Sends activation email.
  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end


  # Sets the password reset attributes.
  def create_reset_digest
    self.reset_token = User.new_token
    update_columns(reset_digest:  User.digest(reset_token), reset_sent_at: Time.zone.now)
    # update_attribute(:reset_digest,  User.digest(reset_token))
    # update_attribute(:reset_sent_at, Time.zone.now)
  end

  # Sends password reset email.
  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  # Returns true if a password reset has expired.
  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end


  # Listings methods
  def listing_already_added?(listing_id)
    listing = Listing.where(id: listing_id).first
    return false unless listing
    employeeships.where(listing_id: listing_id).exists?
  end

  # def under_listing_limit?
  #   (employeeships.count < 10)
  # end

  def can_join_listing?(listing_id)
    #under_listing_limit? &&
    !listing_already_added?(listing_id)
  end

  def user_already_added?(user_id, listing_id)
    user = User.find_by(id: user_id)
    listing = Listing.find_by(id: listing_id)
    return false unless user || listing
    employeeships.where(user_id: user_id, listing_id: listing_id).exists?
  end

  def can_add_user?(user_id, listing_id)
    #under_listing_limit? &&
    !user_already_added?(user_id, listing_id)
  end

  def employeeship_for_listing(user, listing)
    Employeeship.where(:user_id => user.id , :listing_id => listing.id).first
  end

  # def can_edit? listing
  #   # listing.user_id == self.id
  #   listing.user_id == self.id 
  # end

  private

    # Converts email to all lower-case.
    def downcase_email
      # self.email = email.downcase!
      self.email.downcase!
    end

    # Creates and assigns the activation token and digest.
    def create_activation_digest
      self.activation_token  = User.new_token
      self.activation_digest = User.digest(activation_token)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :logged_in_user, only: [:edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy

  def index
    # @users = User.all
    # @users = User.paginate(page: params[:page]).per_page(10)
    @users = User.where(activated: true).paginate(page: params[:page]).per_page(10)
  end

  def show
  	@user = User.find(params[:id])
    redirect_to root_url and return unless @user.activated?
  end

	def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      # log_in @user
    	# flash[:success] = "Welcome to the Sample App!"
      # redirect_to @user
      @user.send_activation_email
      flash[:info] = "Please check your email to activate your account."
      redirect_to root_url
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      # Handle a successful update.
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end

 	private
    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end

  # Before filters

  # def can_edit? listing
  #   listing.user_id == self.id unless current_user.admin?   
  # end

  # Confirms the correct user.
  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end

  # Confirms an admin user.
  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end

end

app/helpers/users_helper.rb
module UsersHelper

	# Returns the Gravatar for the given user.
  def gravatar_for(user, size: 80)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end

	def user_email(user)
		user.email if user && user.email.present?
	end


end

app/views/users/_form_fields.html.erb
<%= render 'shared/error_messages', obj: @user %>

<%= f.label :name %>
<%= f.text_field :name, class: 'form-control' %>

<%= f.label :email %>
<%= f.email_field :email, class: 'form-control' %>

<%= f.label :password %>
<%= f.password_field :password, class: 'form-control' %>

<%= f.label :password_confirmation %>
<%= f.password_field :password_confirmation, class: 'form-control' %>

<%= f.submit yield(:button_text), class: "btn btn-primary" %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 80 %>
  <%= link_to user.name, user %>
  <%# if logged_in? && current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <%# end %>  
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<% provide(:button_text, "Save changes") %>

<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    
    <%= form_for(@user) do |form| %>
      <%= render 'form_fields', f: form %>
    <% end %>

    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <% # For security rel="noopener noreferrer" %>
      <a href="http://gravatar.com/emails" target="_blank" rel="noopener noreferrer">change</a>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>


<%= will_paginate %>

<ul class="users">
  <% @users.each do |user| %>
    <%= render user %>
  <% end %>
</ul>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:button_text, 'Create my account') %>

<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 offset-md-3">
    
    <%= form_for(@user, url: signup_path) do |form| %>
    	<%= render 'form_fields', f: form %>
    <% end %>

     <p>Already have a account? <%= link_to "Sign in!", login_path %></p>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h3>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h3>


      <% if logged_in? %>
        <% if @user.can_add_user?(@user.id, current_user.listings.ids.first)  %>
          <%= link_to 'Add to your listing', employeeships_path(user_id: @user, listing_id: current_user.listings.ids.first), class: "btn-sm btn-info", method: :post %>
        <% else %>
          <span class="badge badge-secondary">
              User already added to your listing
          </span>
        <% end %>
      <% end %>


<%
=begin %>
      <% if @user.can_add_listing?(current_user.listing.id)  %>
        <%= link_to 'Add to team', user_listings_path(user_id: @user.id, listing_id: current_user.listing.id),
                          class: "btn-sm btn-info", method: :post %>
      <% else %>
       <span class="badge badge-secondary">Already in your listing</span>
      <% end %>
<%
=end %>

    </section>
  </aside>
</div>

<%= user_email(@user) %>

<h2>Accepted on listing</h2>
<% @user.accepted_listings.each do |listing| %>
  <h3><%= link_to listing.title, listing_path(listing) %></h3>
  <% if logged_in? %>
    <% if listing.user_id == current_user.id || current_user.id ==  @user.id %>
      <%= link_to 'Delete', employeeship_path(user_id: @user, listing_id: listing), class: "btn-sm btn-danger", method: :delete, data: { confirm: "Are you sure?"} %>
    <% end %>
  <% end %>
<% end %>
<hr>



<h2>Pending on listing</h2>
<% @user.pending_listings.each do |listing| %>
  <h3><%= link_to listing.title, listing_path(listing) %></h3>
  
  <% if logged_in? %>
    <% if listing.user_id == current_user.id || current_user.id == listing.employeeship_for_listing(@user, listing).user_id %>
      <%= link_to 'Cancel', employeeship_path(user_id: @user, listing_id: listing), class: "btn-sm btn-danger", method: :delete, data: { confirm: "Are you sure?"} %>
    <% end %>
  <% end %>

  <% if logged_in? %>
    <% if ( ( employeeship_find(@user,listing).requested_by != current_user.id ) &&
          ( current_user.id == employeeship_find(@user,listing).user_id ) ||
          ( current_user.listings.ids.first ==  employeeship_find(@user,listing).listing_id ) &&
          ( employeeship_find(@user,listing).requested_by == employeeship_find(@user,listing).user_id ) ) %>
      <%= link_to 'Accept', employeeship_path(user_id: @user, listing_id: listing), class: "btn-sm btn-success", method: :put, data: { confirm: "Are you sure?"} %>
    <% end %>
  <% end %>

<% end %>

<hr>

  <h2>My Listing</h2>
  <% if @user.listings.presence  %>
    <% @user.listings.each do |listing| %>
      <h3><%= link_to listing.title, listing_path(listing) %></h3>
      <small>Created <%= time_ago_in_words(listing.created_at) %> ago.</small>
    <% end %>
  <% else %>
    <span class="badge badge-secondary">You did not create any listing yet</span>
    <%= link_to "Create listing now", new_listing_path %>
  <% end %>


<hr>
  <h2>My Pending Users</h2>
  <% if @user.listings.presence  %>
    <% @user.listings.each do |listing| %>
      <% listing.pending_users.each do |user| %>
        <h3><%= link_to user.name, user_path(user) %></h3>
        
        <% if logged_in? %>
          <% if listing.user_id == current_user.id || current_user.id == listing.employeeship_for_listing(user, listing).user_id %>
            <%= link_to 'Cancel', employeeship_path(user_id: user, listing_id: listing), class: "btn-sm btn-danger", method: :delete, data: { confirm: "Are you sure?"} %>
          <% end %>
        <% end %>

        <% if logged_in? %>
          <% if ( ( employeeship_find(user,listing).requested_by != current_user.id ) &&
                ( current_user.id == employeeship_find(user,listing).user_id ) ||
                ( current_user.listings.ids.first ==  employeeship_find(user,listing).listing_id ) &&
                ( employeeship_find(user,listing).requested_by == employeeship_find(user,listing).user_id ) ) %>
            <%= link_to 'Accept', employeeship_path(user_id: user, listing_id: listing), class: "btn-sm btn-success", method: :put, data: { confirm: "Are you sure?"} %>
          <% end %>
        <% end %>

      <% end %>
    <% end %>
  <% end %>

<hr>
  <h2>My Accepted Users</h2>
  <% if @user.listings  %>
    <% @user.listings.each do |listing| %>
      <% listing.accepted_users.each do |user| %>
      <h3><%= link_to user.name, user_path(user) %></h3>
      
      <% if logged_in? %>
        <% if listing.user_id == current_user.id || current_user.id ==  user.id %>
          <%= link_to 'Delete', employeeship_path(user_id: user, listing_id: listing), class: "btn-sm btn-danger", method: :delete, data: { confirm: "Are you sure?"} %>
        <% end %>
      <% end %>


      <% end %>
    <% end %>
  <% end %>