config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'
  get 'password_resets/edit'

	root 'static_pages#home'
	get  '/help',    to: 'static_pages#help'
	get  '/about',   to: 'static_pages#about'
	get  '/contact', to: 'static_pages#contact'

	get  '/signup',  to: 'users#new'
	post '/signup',  to: 'users#create'		# Adding a signup route responding to POST requests for unsubmitted signup form
	resources :users


  resources :listings do
    resource :like, :only => [:create, :destroy]
  end

  resources :employeeships, only: [:create, :destroy, :update]


	# HTTP request	URL		Named route		Action		Purpose
	# GET					/login	login_path		new				page for a new session (login)
	#	POST				/login	login_path		create		create a new session (login)
	#	DELETE			/logout	logout_path		destroy		delete a session (log out)
	get    '/login',   to: 'sessions#new'
	post   '/login',   to: 'sessions#create'
	delete '/logout',  to: 'sessions#destroy'

  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<hr>
<footer class="footer">
  <small class="float-left mt-2">
  </small>
  <nav>
    <ul class="nav justify-content-end">
      <li class="nav-item"><%= link_to "About",   about_path, class: 'nav-link' %></li>
      <li class="nav-item"><%= link_to "Contact", contact_path, class: 'nav-link' %></li>
      <li class="nav-item"><a href="#news" class="nav-link">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="sticky-top">
	<!-- Fixed navbar -->
	<nav class="navbar navbar-expand-md navbar-dark bg-dark">
		<div class="container">
        <%= link_to "Beautybee", root_path , id: "logo", class:'navbar-brand' %>
        <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse justify-content-end collapse" id="navbarCollapse">
          	<ul class="navbar-nav">
            	<li class="nav-item active">
              		<%= link_to "Home",   root_path, class: "nav-link" %>
            	</li>
              <li class="nav-item">
                  <%= link_to "Help",  help_path, class: 'nav-link' %>
              </li>
            	<li class="nav-item">
              		<%= link_to "Listings",  listings_path, class: 'nav-link' %>
            	</li>

              <li class="nav-item"><%= link_to "Users", users_path, class: "nav-link"  %></li>
              <% if logged_in? %>
              <li class="nav-item dropdown">
                <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" "#" id="dropdown05" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Account
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Profile", current_user, class: "dropdown-item" %></li>
                  <li><%= link_to "Settings", edit_user_path(current_user), class: "dropdown-item" %></li>
                  <li class="divider"></li>
                  <li>
                    <%= link_to "Log out", logout_path, method: :delete, class: "dropdown-item" %>
                  </li>
                </ul>
              </li>
            <% else %>
              <li class="nav-item"><%= link_to "Log in", login_path, class: "nav-link" %></li>
            <% end %>
          	</ul>
        </div>
    </div>
</nav>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
  	<%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
      <%= debug(flash) if Rails.env.development? %>
    </div>
  </body>
</html>